/**
 * @file Categories collection — product category tree
 * @summary Organizes the catalog into browsable sections (supplements,
 *          skincare, aloe, gifts, beauty, etc.). Supports nesting via a
 *          self-relation for sub-categories (e.g. Skincare > Moisturizers).
 *
 *          Each category has a localized title + optional image, used
 *          on the category grid section of the homepage and the
 *          `/shop/category/[slug]` listing pages.
 *
 *          Slugs are stable URL identifiers; generate once and do not
 *          change without a redirect.
 */
import type { CollectionConfig } from 'payload'

export const Categories: CollectionConfig = {
  slug: 'categories',
  labels: {
    singular: { en: 'Category', he: 'קטגוריה' },
    plural: { en: 'Categories', he: 'קטגוריות' },
  },
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'parent'],
    group: { en: '📦 Catalog', he: '📦 קטלוג' },
    description: {
      en: 'Categories group products in the storefront. Each product belongs to one category.',
      he: 'קטגוריות עוזרות לקונים למצוא מוצרים באתר (אלוורה, טיפוח, תזונה...). כל מוצר משויך לקטגוריה אחת.',
    },
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      localized: true,
      label: { en: 'Title', he: 'שם הקטגוריה' },
      admin: {
        description: {
          en: 'Shown on the homepage tile and the category browse page.',
          he: 'השם שיופיע על כרטיס הקטגוריה ובדף הקטגוריה באתר. למשל: "אלוורה" או "טיפוח עור".',
        },
      },
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      index: true,
      label: { en: 'Slug', he: 'כתובת באתר' },
      admin: {
        // Auto-generated by the beforeValidate hook below.
        // Hidden from the form so Yarit doesn't have to think about URL slugs.
        hidden: true,
        description: {
          en: 'URL-safe identifier (auto-filled from title).',
          he: 'הכתובת באינטרנט של דף הקטגוריה. נוצרת אוטומטית — אין צורך לגעת.',
        },
      },
      hooks: {
        beforeValidate: [
          ({ value, data }) => {
            if (value) return value
            const title = (data as { title?: string })?.title
            if (!title) return value
            return title
              .toLowerCase()
              .trim()
              .replace(/[^\w\s-]/g, '')
              .replace(/\s+/g, '-')
          },
        ],
      },
    },
    {
      name: 'description',
      type: 'textarea',
      localized: true,
      label: { en: 'Description', he: 'תיאור' },
      admin: {
        description: {
          en: 'Optional short text shown on the category page. 1-2 sentences.',
          he: 'טקסט קצר אופציונלי שמופיע בראש דף הקטגוריה. משפט או שניים.',
        },
      },
    },
    {
      name: 'image',
      type: 'upload',
      relationTo: 'media',
      label: { en: 'Image', he: 'תמונה' },
      admin: {
        description: {
          en: 'Image shown on the category tile in the homepage grid.',
          he: 'התמונה שתופיע על כרטיס הקטגוריה ברשת הקטגוריות בעמוד הבית.',
        },
      },
    },
    {
      name: 'parent',
      type: 'relationship',
      relationTo: 'categories',
      label: { en: 'Parent category', he: 'קטגוריה ראשית' },
      admin: {
        description: {
          en: 'Leave empty for top-level categories.',
          he: 'השאר ריק עבור קטגוריה ראשית (ללא אב).',
        },
      },
    },
    {
      name: 'order',
      type: 'number',
      defaultValue: 0,
      label: { en: 'Sort order', he: 'סדר הצגה' },
      admin: {
        description: {
          en: 'Lower numbers appear first.',
          he: 'מספרים נמוכים יופיעו קודם.',
        },
      },
    },
  ],
}
