/**
 * @file Tags collection — flat product tagging
 * @summary Lightweight labels attached to products (e.g. "vegan",
 *          "gluten-free", "new arrival"). Unlike Categories, tags are
 *          flat — no hierarchy, no images. A product can have many tags.
 *
 *          Used on the storefront for filter chips and in Payload admin
 *          for grouping/filtering in the product list.
 */
import type { CollectionConfig } from 'payload'

export const Tags: CollectionConfig = {
  slug: 'tags',
  labels: {
    singular: { en: 'Tag', he: 'תגית' },
    plural: { en: 'Tags', he: 'תגיות' },
  },
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title'],
    group: { en: '📦 Catalog', he: '📦 קטלוג' },
    // Round 5: Tags collection is hidden from Yarit's sidebar because
    // nothing on the storefront queries `product.tags` — /shop filters
    // by category only. The Tags collection + the Products.tags
    // relationship field stay in the data model so we can re-enable
    // them (in one-line change: flip this to `false`) when tag-based
    // filters ship in a future phase.
    //
    // See: docs/ADMIN-SURFACES.md + Round 5 plan Fix 2.1.
    hidden: true,
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      localized: true,
      label: { en: 'Title', he: 'שם' },
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      index: true,
      label: { en: 'Slug', he: 'כתובת באתר' },
      admin: {
        // Auto-generated by the beforeValidate hook below; hidden so
        // Yarit doesn't see URL slugs in the form.
        hidden: true,
        description: {
          en: 'URL-safe identifier (auto-filled from title).',
          he: 'הכתובת באינטרנט של דף התגית. נוצרת אוטומטית — אין צורך לגעת.',
        },
      },
      hooks: {
        beforeValidate: [
          ({ value, data }) => {
            if (value) return value
            const title = (data as { title?: string })?.title
            if (!title) return value
            return title
              .toLowerCase()
              .trim()
              .replace(/[^\w\s\u0590-\u05FF-]/g, '')
              .replace(/\s+/g, '-')
          },
        ],
      },
    },
  ],
}
