// Shared data + primitives for Living Garden site
const CATALOG = {
  categories: [
    { slug: 'nutrition', he: 'תוספי תזונה', en: 'Nutrition', count: 3, icon: '✿' },
    { slug: 'skincare', he: 'טיפוח עור', en: 'Skincare', count: 2, icon: '❀' },
    { slug: 'aloe', he: 'מוצרי אלוורה', en: 'Aloe', count: 2, icon: '❦' },
    { slug: 'beauty', he: 'יופי', en: 'Beauty', count: 4, icon: '✾' },
    { slug: 'gifts', he: 'מתנות', en: 'Gifts', count: 6, icon: '❧' },
  ],
  products: [
    { slug: 'aloe-drink', he: 'משקה אלוורה ורה בטעם אפרסק', en: 'Aloe Peaches Drink', shortHe: 'משקה אלוורה עדין, 84.3% ג׳ל טהור', shortEn: '84.3% pure aloe gel, preservative-free', price: 155, cat: 'nutrition', featured: true, specimen: '001', plate: 'leaf', badge: 'new' },
    { slug: 'aloe-heat', he: 'קרם אלוורה מחמם', en: 'Aloe Heat Lotion', shortHe: 'עיסוי מחמם לשרירים', shortEn: 'Warming massage for tired muscles', price: 115, cat: 'skincare', specimen: '002', plate: 'ember' },
    { slug: 'aloe-deodorant', he: 'דאודורנט אלוורה טבעי', en: 'Natural Aloe Deodorant', shortHe: 'רול-און טבעי, ללא אלומיניום', shortEn: 'Aluminum-free roll-on', price: 55, cat: 'skincare', specimen: '003', plate: 'cream' },
    { slug: 'aloe-first', he: 'תרסיס אלוורה מרגיע', en: 'Aloe First Spray', shortHe: 'תרסיס רב-שימושי לעור', shortEn: 'All-purpose soothing mist', price: 120, cat: 'aloe', specimen: '004', plate: 'leaf' },
    { slug: 'aloe-toothgel', he: 'משחת שיניים אלוורה ופרופוליס', en: 'Aloe & Propolis Toothgel', shortHe: 'משחת שיניים עדינה, ללא פלואוריד', shortEn: 'Gentle fluoride-free toothgel', price: 45, cat: 'aloe', featured: true, specimen: '005', plate: 'cream' },
    { slug: 'bee-pollen', he: 'אבקת דבורים', en: 'Bee Pollen Tablets', shortHe: 'טבליות אבקת דבורים טבעית', shortEn: 'Rich in B vitamins & amino acids', price: 155, cat: 'nutrition', specimen: '006', plate: 'ember', badge: 'bestseller' },
    { slug: 'bee-propolis', he: 'פרופוליס דבורים', en: 'Bee Propolis Tablets', shortHe: 'תמיכה במערכת החיסון', shortEn: 'Immune system support', price: 165, cat: 'nutrition', specimen: '007', plate: 'leaf' },
    { slug: 'daily-multi', he: 'מולטי ויטמין יומי', en: 'Advanced Daily Multivitamin', shortHe: 'תוסף יומי מקיף', shortEn: 'Comprehensive daily supplement', price: 140, cat: 'nutrition', featured: true, specimen: '008', plate: '' },
  ],
};

const COPY = {
  en: {
    navHome: 'Home', navShop: 'Shop', navJournal: 'Journal', navAbout: 'Our story', navContact: 'Contact',
    heroKicker: 'A small apothecary, grown slowly',
    heroTitle1: 'Wellness that', heroTitle2: 'grows', heroTitle3: 'with you.',
    heroLead: 'Small-batch aloe, bee, and botanical formulas. Hand-selected by Yarit since 2009, shipped across Israel in tissue-wrapped packages.',
    heroCta1: 'Shop the apothecary', heroCta2: 'Read our story',
    statYears: 'Years tending', statProducts: 'Living formulas', statHands: 'Tended by',
    featKicker: 'Now in season',
    featTitle1: 'This', featTitleItalic: 'week\u2019s', featTitle2: 'harvest',
    featLead: 'Eight small-batch favorites, stocked fresh and tied with twine.',
    catKicker: 'Browse the garden',
    catTitle: 'Categories',
    storyKicker: 'Hand-tended since 2009',
    storyTitle1: 'One', storyTitleItalic: 'gardener,', storyTitle2: 'eight hundred kinds of patience.',
    storyP1: 'Yarit started this shop from her kitchen in Tel Aviv with a single aloe leaf and a recipe from her grandmother. Every product still passes through her hands before it reaches yours.',
    storyP2: 'We never rush a formula. Ingredients are foraged or sourced from small Israeli producers, mixed in batches of forty, and rested for two weeks before labeling.',
    storyReadMore: 'Read the long version',
    ingKicker: 'What grows inside',
    ingTitle: 'Four ingredients we come back to',
    ingAloeName: 'Aloe barbadensis', ingAloeDesc: 'Cold-pressed within 6 hours of harvest. The backbone of half the shop.',
    ingHoneyName: 'Wildflower honey', ingHoneyDesc: 'From three small apiaries in the Galilee. Clear, slow, never heated.',
    ingPropolisName: 'Raw propolis', ingPropolisDesc: 'The bees\u2019 own pharmacy. We tincture it ourselves.',
    ingOliveName: 'Ancient olive', ingOliveDesc: 'Single-grove oil, pressed at 27°C to keep the phenols living.',
    quoteKicker: 'From the garden notebook',
    bannerLine: 'Free shipping over ₪200 · 30-day returns · Hand-wrapped orders · Ships within 2 days',
    pdpKicker: 'Signature blend', pdpSize: 'Size', pdpAdd: 'Add to basket', pdpWishlist: 'Save', pdpIncart: 'In basket',
    pdpShipping: 'Ships in 2 days', pdpShippingSub: 'Wrapped in tissue & twine',
    pdpGuarantee: '30-day garden guarantee', pdpGuaranteeSub: 'Return if it doesn\u2019t bloom',
    pdpBatch: 'Batch', pdpBatchSub: 'Hand-poured · 40 bottles',
    pdpNatural: '100% natural', pdpNaturalSub: 'No parabens, ever',
    pdpTab1: 'Story', pdpTab2: 'Ingredients', pdpTab3: 'How to use', pdpTab4: 'Reviews',
    pdpRelated: 'May also please you',
    shopBread: 'Shop', shopTitle1: 'The', shopTitleItalic: 'whole', shopTitle2: 'garden',
    shopLead: 'Every bottle, jar, and tincture we grow.',
    shopCount: '34 products', shopSort: 'Sort by',
    filterCat: 'Category', filterPrice: 'Price', filterConcern: 'Concern', filterStock: 'Availability',
    cartTitle1: 'Your', cartTitleItalic: 'basket', cartLead: 'Three carefully-chosen items, tied with twine.',
    cartEmptyNote: 'Edit the arrangement below — we\u2019ll keep everything fresh.',
    cartSummary: 'Order summary', cartSub: 'Subtotal', cartShip: 'Shipping', cartTax: 'VAT included', cartTotal: 'Total',
    cartPromo: 'Promo code', cartApply: 'Apply', cartCheckout: 'Continue to checkout',
    cartGift: 'Add a hand-written note', cartGiftSub: 'We\u2019ll tuck it inside',
    checkTitle1: 'Gentle', checkTitleItalic: 'checkout',
    checkStep1: 'Details', checkStep2: 'Shipping', checkStep3: 'Payment',
    checkContact: 'Contact', checkDeliver: 'Deliver to', checkPayment: 'Payment',
    checkFirst: 'First name', checkLast: 'Last name', checkEmail: 'Email', checkPhone: 'Phone',
    checkAddr: 'Street & number', checkCity: 'City', checkPost: 'Postal code', checkCountry: 'Country',
    checkNote: 'A note for the wrapper (optional)',
    checkPlace: 'Place order — ₪515',
    aboutKicker: 'Our story', aboutTitle1: 'A kitchen,', aboutTitleItalic: 'a window,', aboutTitle2: 'and one aloe plant.',
    aboutLead: 'Fourteen years on, this is still a small shop with long friendships.',
    accountTitle: 'Garden account',
    accountHi: 'Welcome back,', accountName: 'Rachel',
    accountOrders: 'Orders', accountFav: 'Wishlist', accountAddr: 'Addresses', accountSubs: 'Subscriptions', accountSettings: 'Preferences',
    accountRecent: 'Recent orders',
    accountPointsLabel: 'Garden points', accountPointsNote: 'Worth ₪124 at checkout',
    footerTag: 'Small-batch wellness, hand-wrapped in Tel Aviv. Since 2009.',
    footerShop: 'Shop', footerInfo: 'Information', footerSupport: 'Help',
    footerNews: 'Notes from the garden', footerNewsSub: 'One letter a month. No spam, some seeds.',
    footerSubscribe: 'Subscribe',
    footerRights: '© 2026 Yarit Eitan · Tel Aviv',
  },
  he: {
    navHome: 'דף הבית', navShop: 'חנות', navJournal: 'יומן', navAbout: 'הסיפור שלנו', navContact: 'צור קשר',
    heroKicker: 'בית מרקחת קטן שצומח לאט',
    heroTitle1: 'בריאות שצומחת', heroTitle2: 'אִתָּךְ', heroTitle3: ', יום אחר יום.',
    heroLead: 'נוסחאות אלוורה, דבש וצמחים במנות קטנות. נבחרות ביד על ידי ירית מ-2009, עטופות בנייר משי ונשלחות לכל הארץ.',
    heroCta1: 'לחנות הבית מרקחת', heroCta2: 'הסיפור שלנו',
    statYears: 'שנים של טיפוח', statProducts: 'נוסחאות חיות', statHands: 'בידי',
    featKicker: 'קטיף השבוע',
    featTitle1: 'היבול', featTitleItalic: 'של', featTitle2: 'השבוע',
    featLead: 'שמונה מועדפים בייצור קטן, טריים וקשורים בחוט פשתן.',
    catKicker: 'מטיילים בגן',
    catTitle: 'קטגוריות',
    storyKicker: 'בעבודת יד מאז 2009',
    storyTitle1: 'גננת', storyTitleItalic: 'אחת,', storyTitle2: 'שמונה מאות סוגי סבלנות.',
    storyP1: 'ירית התחילה את החנות במטבח שלה בתל אביב עם עלה אלוורה אחד ומתכון של סבתא. כל מוצר עובר דרך הידיים שלה לפני שהוא מגיע אליך.',
    storyP2: 'אנחנו לא ממהרות עם נוסחה. החומרים נאספים או מגיעים מיצרנים ישראלים קטנים, מעורבבים במנות של ארבעים, ונחים שבועיים לפני התיוג.',
    storyReadMore: 'הסיפור המלא',
    ingKicker: 'מה גדל בפנים',
    ingTitle: 'ארבעה חומרים שאנחנו חוזרות אליהם',
    ingAloeName: 'אלוורה ברברדנסיס', ingAloeDesc: 'נסחטת בכבישה קרה תוך 6 שעות מהקטיף. עמוד השדרה של חצי מהחנות.',
    ingHoneyName: 'דבש פרחי בר', ingHoneyDesc: 'משלוש מכוורות קטנות בגליל. צלול, איטי, לא מחומם.',
    ingPropolisName: 'פרופוליס גולמי', ingPropolisDesc: 'בית המרקחת של הדבורים. אנחנו מכינות את התמצית בעצמנו.',
    ingOliveName: 'זית עתיק', ingOliveDesc: 'שמן מכרם יחיד, נסחט ב-27°C כדי לשמור על הפנולים חיים.',
    quoteKicker: 'מיומן הגן',
    bannerLine: 'משלוח חינם מעל ₪200 · החזרה תוך 30 יום · עטיפה בעבודת יד · שולח תוך יומיים',
    pdpKicker: 'נוסחה חתומה', pdpSize: 'גודל', pdpAdd: 'הוסף לסל', pdpWishlist: 'שמור', pdpIncart: 'בסל',
    pdpShipping: 'נשלח תוך יומיים', pdpShippingSub: 'עטוף בנייר משי וחוט',
    pdpGuarantee: 'אחריות 30 יום', pdpGuaranteeSub: 'אפשר להחזיר',
    pdpBatch: 'מנה', pdpBatchSub: 'ביד · 40 בקבוקים',
    pdpNatural: '100% טבעי', pdpNaturalSub: 'ללא פרבנים, לעולם',
    pdpTab1: 'סיפור', pdpTab2: 'חומרים', pdpTab3: 'איך להשתמש', pdpTab4: 'ביקורות',
    pdpRelated: 'אולי גם תאהבו',
    shopBread: 'חנות', shopTitle1: 'כל', shopTitleItalic: 'הגן', shopTitle2: ' ',
    shopLead: 'כל בקבוק, צנצנת ותמצית שאנחנו מגדלות.',
    shopCount: '34 מוצרים', shopSort: 'מיין לפי',
    filterCat: 'קטגוריה', filterPrice: 'מחיר', filterConcern: 'אזור טיפול', filterStock: 'זמינות',
    cartTitle1: 'הסל', cartTitleItalic: 'שלך', cartLead: 'שלושה פריטים נבחרים, קשורים בחוט.',
    cartEmptyNote: 'אפשר לערוך את הסידור למטה — אנחנו נשמור הכל טרי.',
    cartSummary: 'סיכום הזמנה', cartSub: 'סכום ביניים', cartShip: 'משלוח', cartTax: 'כולל מע״מ', cartTotal: 'סה״כ',
    cartPromo: 'קוד הטבה', cartApply: 'הפעל', cartCheckout: 'המשך לתשלום',
    cartGift: 'הוסיפי פתק בכתב יד', cartGiftSub: 'נצרף בפנים',
    checkTitle1: 'תשלום', checkTitleItalic: 'עדין',
    checkStep1: 'פרטים', checkStep2: 'משלוח', checkStep3: 'תשלום',
    checkContact: 'פרטי קשר', checkDeliver: 'משלוח אל', checkPayment: 'אמצעי תשלום',
    checkFirst: 'שם פרטי', checkLast: 'שם משפחה', checkEmail: 'אימייל', checkPhone: 'טלפון',
    checkAddr: 'רחוב ומספר', checkCity: 'עיר', checkPost: 'מיקוד', checkCountry: 'מדינה',
    checkNote: 'פתק לעטיפה (לא חובה)',
    checkPlace: 'בצע הזמנה — ₪515',
    aboutKicker: 'הסיפור שלנו', aboutTitle1: 'מטבח,', aboutTitleItalic: 'חלון,', aboutTitle2: 'ועלה אלוורה אחד.',
    aboutLead: 'ארבע עשרה שנים אחר כך — עדיין חנות קטנה עם חברויות ארוכות.',
    accountTitle: 'חשבון בגן',
    accountHi: 'ברוכה השבה,', accountName: 'רחל',
    accountOrders: 'הזמנות', accountFav: 'מועדפים', accountAddr: 'כתובות', accountSubs: 'מנויים', accountSettings: 'העדפות',
    accountRecent: 'הזמנות אחרונות',
    accountPointsLabel: 'נקודות גן', accountPointsNote: 'שווה ₪124 בקופה',
    footerTag: 'בריאות בעבודת יד, עטופה בתל אביב. מ-2009.',
    footerShop: 'חנות', footerInfo: 'מידע', footerSupport: 'עזרה',
    footerNews: 'מכתבים מהגן', footerNewsSub: 'מכתב בחודש. בלי ספאם, כמה זרעים.',
    footerSubscribe: 'הרשמה',
    footerRights: '© 2026 ירית איתן · תל אביב',
  },
};

window.CATALOG = CATALOG;
window.COPY = COPY;
